version: '3.8'

services:
  starter-node-repo:
    build:
      args:
        NODE_ENV: development
    image: starter-node-repo-development
    container_name: starter-node-repo-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src/:/home/node/app/src/
      - ./package.json:/home/node/app/package.json
